name: Tester
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install action dependencies
        run: cd .github/actions/tester && npm ci

      - name: Set Git Short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - uses: ./.github/actions/tester
        with:
          build-args: |
            version=${{ env.SHORT_SHA }}
