name: Services@node 17
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test-services-17:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 17
        env:
          NPM_CONFIG_ENGINE_STRICT: 'false'

      - name: Service tests
        uses: ./.github/actions/service-tests
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
