name: Services@node 17
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test-services-17:
    runs-on: ubuntu-latest
    env:
      PAT_EXISTS: ${{ secrets.GH_PAT != '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 17
        env:
          NPM_CONFIG_ENGINE_STRICT: 'false'

      - name: Service tests (with PAT)
        if: ${{ env.PAT_EXISTS == 'true' }}
        uses: ./.github/actions/service-tests
        with:
          github-token: '${{ secrets.GH_PAT }}'

      - name: Service tests (with workflow token)
        if: ${{ env.PAT_EXISTS == 'false' }}
        uses: ./.github/actions/service-tests
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
