name: Services
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  test-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 16

      - name: Service tests
        uses: ./.github/actions/service-tests
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
